<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>Pathoschild.ModData.UpdateAggregates</RootNamespace>
	</PropertyGroup>
	
	<ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SMAPI.Toolkit" HintPath="$(SmapiPath)\smapi-internal\SMAPI.Toolkit.dll" Private="true" />
		<Reference Include="SMAPI.Toolkit.CoreInterfaces" HintPath="$(SmapiPath)\smapi-internal\SMAPI.Toolkit.CoreInterfaces.dll" Private="true" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.jsonc" CopyToOutputDirectory="PreserveNewest" />
		<None Update="appsettings.local.jsonc" CopyToOutputDirectory="PreserveNewest" Condition="Exists('appsettings.local.jsonc')" />
	</ItemGroup>
</Project>
